### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by lordcrekit** [lordcrekit/MI-449-SS17-740-js-intro-Vh2K33#1]
@egillespie Can you take a look at this? It's [hosted here](https://lordcrekit.github.io/MI-449-SS17-740-js-intro-Vh2K33/) and meets the following criteria:

- [x] At least 3 `button` elements are included in your page
- [x] When each of the buttons are hovered over (`mouseenter` event) or clicked on (`click` event), a unique sound effect plays from an `audio` element (try the `.play()` method) -- you may use [these drum kit sounds](/static/audio/drum-sounds.zip), create ones from [this sound effects generator](http://sfbgames.com/chiptone/), or use any other sounds that won't hurt/irritate the people who listen to them
- [x] Each button is well-labeled, corresponding to the sound it will play
- [x] All `audio` elements are invisible (no `controls` attribute), so that they can only be played with the buttons
- [x] All of your JavaScript is in a separate file ending with `.js`

I had to add a random blank file just to get github pages to reload the project, because it only loaded like half the files the first time it tried- what?

EDIT: I had no sound on the computer I made this on, so the sounds may be a bit unpredictable.

**Comment by egillespie** [comment]
This is a nice looking page!

GitHub Pages is a fickle beast, sometimes it takes pushing arbitrary changes in order for it to work. Sometimes it can also just take a long time to pick up your changes (I've had it take up to 30 minutes even!).

We'll talk about how we handle this. For now, keep retrying till it works and point it out to us like you've done here so we can track how much trouble this is causing students!

Here's some feedback about your code:

### Avoid using `concat`

You can use the `+` operator to concatenate strings and it's much faster (less typing, but also [runs faster](http://jsperf.com/concat-vs-plus-vs-join)) than `concat`. You also don't need to call `toString()`. Numbers will automatically be converted to strings when concatenating using `+`.

### Link to sounds with `audio` element

We'd like you to use `audio` elements in your HTML to manage your sound. Loading your sound this way allows someone to change the sounds without needing to make JavaScript changes. It also means the browser can pre-load sounds so they are ready to play immediately instead of downloading them when the JavaScript runs.

Check out criteria 2 and 4 for notes about how to use JavaScript to play sound in an `audio` element.

---

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! :rocket:

**Comment by lordcrekit** [comment]
Done and done.

Wow, + runs a LOT faster than concat!

**Comment by egillespie** [comment]
Yeah it does! Good work on the changes, your code looks great! :shipit:
